### ISSUE TITLE
NHSD dev install checklist

### ISSUE THREAD

**Issue by bloodearnest** [opensafely-core/backend-server#26]
Rough plan of  steps needed to install the job-runner on NHSD vm.

I'm sure we'll hit some bumps along the road.

- [ ] **1. Check proxy details, add to shell env if needed**

`export HTTPS_PROXY=http://proxy:port`

- [ ] **2. Check that local docker daemon is configured to use proxy**

See https://docs.docker.com/config/daemon/systemd/#httphttps-proxy.

To test: `docker pull docker-proxy.opensafely.org/opensafely-core/python`

Note: if docker daemon is exposed over HTTPS, then may need to add `NO_PROXY=https://docker-endpoint` to the environment.

- [ ] **3. Checkout backend-servers repo**

`git clone https://github-proxy/opensafely-core/backend-server`

Note this can be checked out anywhere, it doesn't matter.

- [ ] **4. Run the manage.sh script from the checkout**

`sudo ./nhsd-backend/manage.sh`

You can check this out, and also scripts/jobrunner.sh, but they essentially do the following

 - install python + docker dependencies (should be a no-op as you've already done them)
 - create a jobrunner user to manage it (and some limited sudo rules to allow it to restart the service)
 - set up the jobrunner application in /srv/job-runner
 - set up some workspace directories in /srv/{medium,high}_privacy
 - install a systemd service called `jobrunner` to manage it.
 - pull down some docker images

- [ ] **5. Switch to jobrunner user**

`sudo su - jobrunner`

- [ ] **6. Configure the secrets** - edit `/srv/jobrunner/environ/02_secrets.env` and add secrets Datalab will provide
   * JOB_SERVER_TOKEN
   * PRIVATE_REPO_ACCESS_TOKEN
   * STATA_LICENSE (this will need updating)
   * FULL_DATABASE_URL (in the form `spark://$USER:$PASSWORD@$HOST:$PORT/$DB?http_path=$HTTP_PATH`)

- [ ] **7. Add HTTPS_PROXY env var  to /srv/jobrunner/environ/04_local.env**

`HTTPS_PROXY=http://proxy:port`

Note: will also need NO_PROXY if we added it above.

- [ ] **7a: pull the new cohortextractor iamge**

From `/srv/jobrunner/code`:

`./scripts/update-docker-image.sh cohortextractor-v2`

- [ ] **8. Reload jobrunner**

`sudo systemctl restart jobrunner`

- [ ] **9. Check logs to see if it's up and running**

`journalctl -xe -u jobrunner`

- [ ] **10: run test job locally**

From `/srv/jobrunner/code`:

`python3 -m jobrunner.cli.add_job https://github.com/opensafely/databricks-test run_all`

This should print some data to the terminal. You can then check if the job succeeded with 

`journalctl -feu jobrunner`

- [ ] **11. Datalab to submit test job**

Final step is testing that a job submitted and jobs.opensafely.org can run, which currently only Datalab can do, but plan is to give test accounts to NHSD.

Check the logs as above to verify the job ran successfully.
